### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by platisd** [Trooper98/DIT112-SmartCar#3]
Congrats on having the repository public!

However, its contents are not as usable as they would be were they accompanied by a nice `README.md file`. The `README` that explains **what** is this project about, **why** you chose to do it (i.e. the problem it solves) and **how** you did it! :+1: 

A nice reading can be found [here](https://open-source-guide.18f.gov/making-readmes-readable/).

**Comment by platisd** [comment]
A video would be nice as well! :+1:

**Comment by this-oliver** [comment]
this is long over due but finally completed :) Thanks for the notice!! (ps: would've added a video but don't know how too... I guess a link to a video will have to suffice :D )

**Comment by platisd** [comment]
:+1:

**Comment by platisd** [comment]
:+1: Don't forget #4 though! :smile:
